# NG_program_work_1&2_Numpy＆Logistic&NN

吴恩达 Coursera 课程 DeepLearning.ai 编程作业系列，
本文为“**神经网络与深度学习**”部分的第二周“**神经网络基础**”的课程作业（做了无用部分的删减）。

另外，本节课程笔记在此：“[吴恩达Coursera深度学习课程DeepLearning.ai提炼笔记（1-2）](http://blog.csdn.net/koala_tree/article/details/78045596) ”，如有任何建议和问题，欢迎留言。



# 第1部分：使用Numpy的Python基础（可选赋值）
#  1 - 用numpy建立基本功能
Numpy是Python中科学计算的主要软件包。它由一个大型社区维护（www.numpy.org）。在本练习中，您将学习np.exp，np.log和np.reshape等几个重要的numpy函数。您需要知道如何使用这些功能进行未来分配。

### 1.1 - sigmoid函数，np.exp（）
练习：构建一个返回实数x的S型函数的函数。对指数函数使用math.exp（x）。

提醒：有时也被称为后勤功能。它是一种非线性函数，不仅用于机器学习（Logistic回归），还用于深度学习。<br/>
$sig(t)=\frac{1}{1+e^{-x}}$
![image.png](https://img-blog.csdn.net/20170921212049012?watermark/2/text/aHR0cDovL2Jsb2cuY3Nkbi5uZXQvS29hbGFfVHJlZQ==/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70/gravity/SouthEast)
要引用属于特定包的函数，可以使用package_name.function（）来调用它。运行下面的代码以查看math.exp()的示例。

In [1]:
# GRADED FUNCTION: basic_sigmoid

import math

def basic_sigmoid(x):
    """
    Compute sigmoid of x.

    Arguments:
    x -- A scalar

    Return:
    s -- sigmoid(x)
    """

    ### START CODE HERE ### (≈ 1 line of code)
    s = 1.0 / (1 + 1/ math.exp(x))
    ### END CODE HERE ###

    return s

In [2]:
basic_sigmoid(3)

0.9525741268224334

实际上，我们很少在深度学习中使用“数学”库，因为函数的输入是实数。在深度学习中，我们大多使用矩阵和向量。这就是为什么numpy更有用。

In [3]:
### One reason why we use "numpy" instead of "math" in Deep Learning ###
x = [1, 2, 3]
basic_sigmoid(x) # you will see this give an error when you run it, because x is a vector.

TypeError: must be real number, not list

事实上，如果x = （x1，x2，。。。，xñ）是一个行向量，然后n p 。e x p （x ）将指数函数应用于x的每个元素。输出结果是：n p

In [4]:
import numpy as np

# example of np.exp
x = np.array([1, 2, 3])
print(np.exp(x)) # result is (exp(1), exp(2), exp(3))

[  2.71828183   7.3890561   20.08553692]


而且，如果x是一个向量，那么就是一个Python操作，例如s = x + 3或者s = 1X 将输出s作为与x相同大小的向量。

In [5]:
# example of vector operation
x = np.array([1, 2, 3])
print (x + 3)

[4 5 6]


**练习**：使用numpy实现sigmoid函数。

**说明**：x现在可以是实数，矢量或矩阵。我们用numpy来表示这些形状（向量，矩阵...）的数据结构被称为numpy数组。现在你不需要知道更多。

$$
\text{For } x \in \mathbb{R}^n \text{,     } sigmoid(x) = sigmoid\begin{pmatrix}
    x_1  \\
    x_2  \\
    ...  \\
    x_n  \\
\end{pmatrix} = \begin{pmatrix}
    \frac{1}{1+e^{-x_1}}  \\
    \frac{1}{1+e^{-x_2}}  \\
    ...  \\
    \frac{1}{1+e^{-x_n}}  \\
\end{pmatrix}\tag{1}
$$

In [6]:
# GRADED FUNCTION: sigmoid

import numpy as np # this means you can access numpy functions by writing np.function() instead of numpy.function()

def sigmoid(x):
    """
    Compute the sigmoid of x

    Arguments:
    x -- A scalar or numpy array of any size

    Return:
    s -- sigmoid(x)
    """

    ### START CODE HERE ### (≈ 1 line of code)
    s = 1.0 / (1 + 1 / np.exp(x))
    ### END CODE HERE ###

    return s


x = np.array([1, 2, 3])
sigmoid(x)

array([ 0.73105858,  0.88079708,  0.95257413])

### 1.2 - Sigmoid gradient
**练习**：实现函数sigmoid_grad（）来计算sigmoid函数相对于其输入x的梯度。公式是：
$$sigmoid\_derivative(x) = \sigma'(x) = \sigma(x) (1 - \sigma(x))\tag{2}$$

您经常通过两步来编写此函数：<br>
1.将s设置为x的S形。你可能会发现你的sigmoid（x）函数很有用。<br>
2.计算
$$\sigma'(x) = s(1-s)$$

In [7]:
# GRADED FUNCTION: sigmoid_derivative

def sigmoid_derivative(x):
    """
    Compute the gradient (also called the slope or derivative) of the sigmoid function with respect to its input x.
    You can store the output of the sigmoid function into variables and then use it to calculate the gradient.

    Arguments:
    x -- A scalar or numpy array

    Return:
    ds -- Your computed gradient.
    """

    ### START CODE HERE ### (≈ 2 lines of code)
    s = 1.0 / (1 + 1 / np.exp(x))
    ds = s * (1 - s)
    ### END CODE HERE ###

    return ds


x = np.array([1, 2, 3])
print ("sigmoid_derivative(x) = " + str(sigmoid_derivative(x)))

sigmoid_derivative(x) = [ 0.19661193  0.10499359  0.04517666]


### 1.3 - 重新整形数组
深度学习中使用的两种常见numpy函数是[np.shape](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.shape.html)和[np.reshape（）](https://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html)。 
- X.shape用于获取矩阵/向量X的形状（维度）。 
- X.reshape（...）用于将X重新整形为其他维度。

例如，在计算机科学中，图像是由形状的三维阵列表示。然而，当你读取的图像作为算法的输入将其转换为的形状的矢量。换句话说，您将3D数组“展开”或重新塑造成一维矢量。
![](https://img-blog.csdn.net/20170921213238525?watermark/2/text/aHR0cDovL2Jsb2cuY3Nkbi5uZXQvS29hbGFfVHJlZQ==/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70/gravity/SouthEast)

**练习**：执行<font color=red>image2vector()</font>需要形状（长度，高度，3）的输入并返回形状的矢量（长度*高度* 3,1）。例如，如果您想将shape（a，b，c）的数组v重塑为形状矢量（a * b，c），您可以这样做：

In [8]:
v = v.reshape((v.shape[0]*v.shape[1], v.shape[2])) # v.shape[0] = a ; v.shape[1] = b ; v.shape[2] = c

NameError: name 'v' is not defined

请不要将图像的尺寸硬编码为常量。而是查找您需要的数量image.shape[0]等。

In [9]:
# GRADED FUNCTION: image2vector
def image2vector(image):
    """
    Argument:
    image -- a numpy array of shape (length, height, depth)

    Returns:
    v -- a vector of shape (length*height*depth, 1)
    """

    ### START CODE HERE ### (≈ 1 line of code)
    v = image.reshape((image.shape[0] * image.shape[1] * image.shape[2], 1))
    ### END CODE HERE ###

    return v

# This is a 3 by 3 by 2 array, typically images will be (num_px_x, num_px_y,3) where 3 represents the RGB values
image = np.array([[[ 0.67826139,  0.29380381],
        [ 0.90714982,  0.52835647],
        [ 0.4215251 ,  0.45017551]],

       [[ 0.92814219,  0.96677647],
        [ 0.85304703,  0.52351845],
        [ 0.19981397,  0.27417313]],

       [[ 0.60659855,  0.00533165],
        [ 0.10820313,  0.49978937],
        [ 0.34144279,  0.94630077]]])

print ("image2vector(image) = " + str(image2vector(image)))

image2vector(image) = [[ 0.67826139]
 [ 0.29380381]
 [ 0.90714982]
 [ 0.52835647]
 [ 0.4215251 ]
 [ 0.45017551]
 [ 0.92814219]
 [ 0.96677647]
 [ 0.85304703]
 [ 0.52351845]
 [ 0.19981397]
 [ 0.27417313]
 [ 0.60659855]
 [ 0.00533165]
 [ 0.10820313]
 [ 0.49978937]
 [ 0.34144279]
 [ 0.94630077]]


### 1.4 - 规范化行
我们在机器学习和深度学习中使用的另一种常用技术是规范化我们的数据。它经常导致更好的性能，因为梯度下降在归一化后收敛得更快。在这里，通过标准化我们的意思是将x改为$\frac{x}{\| x\|}$将x的每个行向量除以其规范）。<br>
例如，如果
$$x = 
\begin{bmatrix}
    0 & 3 & 4 \\
    2 & 6 & 4 \\
\end{bmatrix}\tag{3}
$$
then
$$
\| x\| = np.linalg.norm(x, axis = 1, keepdims = True) = \begin{bmatrix}
    5 \\
    \sqrt{56} \\
\end{bmatrix}\tag{4}
$$
and
$$
x\_normalized = \frac{x}{\| x\|} = \begin{bmatrix}
    0 & \frac{3}{5} & \frac{4}{5} \\
    \frac{2}{\sqrt{56}} & \frac{6}{\sqrt{56}} & \frac{4}{\sqrt{56}} \\
\end{bmatrix}\tag{5}
$$

Note that you can divide matrices of different sizes and it works fine: this is called broadcasting and you’re going to learn about it in part 5.

**Exercise**: Implement normalizeRows() to normalize the rows of a matrix. After applying this function to an input matrix x, each row of x should be a vector of unit length (meaning length 1).


请注意，您可以分割不同大小的矩阵，并且它可以正常工作：这称为广播，您将在第5部分中了解它。

**练习**：实现normalizeRows（）来规范矩阵的行。将这个函数应用到输入矩阵x后，x的每一行应该是单位长度的向量（意思是长度1）。

In [11]:
# GRADED FUNCTION: normalizeRows

def normalizeRows(x):
    """
    Implement a function that normalizes each row of the matrix x (to have unit length).

    Argument:
    x -- A numpy matrix of shape (n, m)

    Returns:
    x -- The normalized (by row) numpy matrix. You are allowed to modify x.
    """

    ### START CODE HERE ### (≈ 2 lines of code)
    # Compute x_norm as the norm 2 of x. Use np.linalg.norm(..., ord = 2, axis = ..., keepdims = True)
    x_norm = np.linalg.norm(x, axis=1, keepdims = True)  #计算每一行的长度，得到一个列向量

    # Divide x by its norm.
    x = x / x_norm  #利用numpy的广播，用矩阵与列向量相除。
    ### END CODE HERE ###

    return x

x = np.array([
    [0, 3, 4],
    [1, 6, 4]])
print("normalizeRows(x) = " + str(normalizeRows(x)))

normalizeRows(x) = [[ 0.          0.6         0.8       ]
 [ 0.13736056  0.82416338  0.54944226]]


**Note**: 
In normalizeRows(), you can try to print the shapes of x_norm and x, and then rerun the assessment. You’ll find out that they have different shapes. This is normal given that x_norm takes the norm of each row of x. So x_norm has the same number of rows but only 1 column. So how did it work when you divided x by x_norm? This is called broadcasting and we’ll talk about it now!

**注意**：
在normalizeRows（）中，您可以尝试打印x_norm和x的形状，然后重新运行评估。你会发现他们有不同的形状。这是正常的，因为x_norm取x的每一行的范数。所以x_norm具有相同的行数，但只有1列。那么当你将x除以x_norm时它是如何工作的？这就是所谓的广播，我们现在就来谈谈吧！